### ISSUE TITLE
Instagram Basic Display EOL

### ISSUE THREAD

**Issue by ulriklpedersen** [svenpet90/instagram#30]
I can't provide much technical information but a huge update seems to be required.

https://developers.facebook.com/blog/post/2024/09/04/update-on-instagram-basic-display-api/

**Comment by svenpet90** [comment]
Thank you for creating this issue!

This will indeed be the end of this extension - at least in its current implementation.

I'll add a hint in the README adressing this upcoming change.

I will also have a look if its feasable to refactor this extensions logic to Use the new API. But cannot promise anything.

Each and every helping hand would be greatly appreciated 😇

**Comment by svenpet90** [comment]
I've had the time to do through the Docs for the new "Instagram API with Instagram Login" which is what is needed now.

I just created an issue #31  to gather and document all needed changes in order to refactor this extension to use this new API.

Some preliminary tests suggest that it more or less works the same, only the authorization process is a bit different

**Comment by svenpet90** [comment]
Update: I just released v3 of this extension using the new API.
Upgrading is rather simple, see the "upgrade" section in the README :)
